### ISSUE TITLE
Losing Admin Privileges Due to Community Server Name Tags

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#100]
Some servers put labels or other tags in front of the username which nullifies the admin privileges and leads to several problems with !clear and !gpt4 admin commands. This issue persists in other features that have something to do with usernames.

Example:
```
[Player] punching bag: !clear \global
Clearing chat history for user '[Player]  punching bag'.
*SPEC* punching bag: !clear \global
Clearing chat history for user '*SPEC* punching bag'.
*SPEC* [Player] punching bag: !pcc I will burn this planet down
[*SPEC* [Play..] hahaha what you got against earth?
      ^ Who is he referring to? (I can bump up the shortened username limit but it defeats its purpose)
```

Possible solution: A code that will look into the `tags.json` file and strip off the included tags. Also, a GUI command that allows you to add tags like in a ban feature.
```
> tag uwu
[01:54:50] -- TAGGED 'uwu'
> untag uwu
[01:54:55] -- UNTAGGED 'uwu'

**Comment by dborodin836** [comment]
This PR pretty much resolves this issue, but I'd do some additional testing later.
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/88435653/36fbb016-304c-4a1b-b1d3-52d584e53862)

**Comment by teufortressIndustries** [comment]
Thanks, King, I will try this later.
