### ISSUE TITLE
GroqCloud support?

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#103]
The introduction of Llama3 by Meta, which approaches the capabilities of GPT4, has led to its inclusion in Groq's suite of available models. Unfortunately, my current hardware cannot support these models at a decent speed. However, Groq can, achieving approximately 300tps at relatively low costs, and is currently offering a free beta.
https://console.groq.com/playground
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/51a27eb8-ce59-490b-8a52-5a58228b7489)
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/73853ffd-c28c-40a2-9ae9-affc3545d43a)

**Comment by dborodin836** [comment]
Hi, @teufortressIndustries.

Yeah, thats nice idea, gonna implement it soon. 👍
