### ISSUE TITLE
Message sending delay (+queueing)

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#77]
Some servers don't allow messages to be sent too quickly, so I think adding a customizable delay before sending a continuation of the previous message might prevent this. And when multiple users are using the bot, I would like the bot to finish sending the first message it generated first, before sending the next ones. (Or somehow label the message so that it is clear who it is being sent to)

![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/450e1c05-2dac-4cdb-9b5a-842da0e4cd72)

**Comment by dborodin836** [comment]
Hi @teufortressIndustries.

Thanks for bringing up this issue.

I have made several key enhancements based on your feedback:
* Added customizable delay before sending a message to prevent issues with servers that have rate limits.

* Implemented a message queue system to ensure that the bot completes sending the first generated message before moving on to the next ones, especially when multiple users are using the bot simultaneously.

* Introduced a labeling system with shortened usernames, making it clear who each message is being sent to.

* Introducing the ConfirmableQueue: an experimental feature for improved message delivery reliability. It includes checks for user muting and ensures successful message transmission. Please exercise caution as it may introduce unexpected behavior or performance issues compared to the standard approach.

**Comment by teufortressIndustries** [comment]
Thanks again for the great work you have done.
