### ISSUE TITLE
The program does not see the command on some servers

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#80]
(I changed the !gpt3 to !ai, it works fine)
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/47e35ba7-acc1-493b-bcac-d8570055328f)
server on screenshot: 162.248.94.182:27015
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/796ccd6f-8166-4eea-b62e-9e5e600142cc)
ignore the "Couldn't connect" warning, tf2 wasn't launched at that moment.

Maybe because of the score on the left side of the nickname? There was a server where tf2 and discord chat were connected and people on discord couldn't get the AI working, while others could (they had a "discord" tag at the left side of their nickname)
server I'm talking about: 172.232.147.231:27016 (it's empty most of the time)

here's the console log even if you might not need it:
[console.log](https://github.com/dborodin836/TF2-GPTChatBot/files/13849850/console.log)

**Comment by dborodin836** [comment]
Hi @teufortressIndustries.

Thanks for bringing up this issue.

I believe their plugin, which adds the Discord tag and score, may have interfered with the default Valve chat format settings. Valve servers typically use two spaces after the colon symbol (<username>_:__<message>), but some servers use only one. I have implemented a check for this issue, and it should now be working fine.

**Comment by teufortressIndustries** [comment]
Works like a charm
![image](https://github.com/dborodin836/TF2-GPTChatBot/assets/80442847/5f67773a-ffa1-4436-9f96-cbab58e6ba4f)
