### ISSUE TITLE
Using a "system" role instead of putting instructions into the user prompt

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#88]
It should be easy to do.

I think something like:
```py
conversation_history.append({"role": "system", "content": f" Answer in less than {config.SOFT_COMPLETION_LIMIT} chars! {config.CUSTOM_PROMPT}"})
```
should do the job?
[I've read that it's better to add the system at the end, after the user's prompt.
](https://community.openai.com/t/the-system-role-how-it-influences-the-chat-behavior/87353)My brain power is not enough to turn this into a pr, sorry.

**Comment by dborodin836** [comment]
Hi @teufortressIndustries.

Thanks for bringing up this issue. I've testted all of the variants present in that thread.

1. Sending the "system" content as "user" content (appending the "system" content to a "user" prompt) [[Example]](https://pastebin.com/KSCr8aQY):
   - This is the current implementation and although it may not be preferred approach, but it works perfectly.

2. Sending the "system" content after each "user" content  [[Example]](https://pastebin.com/u9Jgwuyv):
   - This variant, where the system content is added after every user content, also works well. It provides consistency throughout the conversation.

3. Sending the "system" content at the beginning of the messages array  [[Example]](https://pastebin.com/k8rpZXUS):
   - While this approach generally works, there appears to be an issue with maintaining the required message length when using GPT-3. However,  GPT-4 works well. In the future, I may consider this approach, but it would require some adjustments to work seamlessly with GPT-3.

4. Sending the "system" content as the very last "messages" array object [[Example]](https://pastebin.com/MLnWMtER):
   - This variant also functions well, but it has the downside of requiring users to type a custom prompt flag every time they submit the prompt (e.g., `\medic`).

To wrap it up, it seems like the current implementation of appending the system content to the user prompt is working well enough. I'll look for the adjustments that will make migration to the second option possible.
