### ISSUE TITLE
Better Chat Conversation History? User Isolation and Nickname Features.

### ISSUE THREAD

**Issue by teufortressIndustries** [dborodin836/TF2-GPTChatBot#95]
Hello again. So, have you noticed that the !chat command is kinda throwing everyone's messages into one big pot? That's definitely a recipe for chaos. This can lead to several problems due to spammers, preventing an adequate conversation with the chatbot.
I've got a couple of ideas to tidy things up:
- Make chat isolation for each user (separate chat history for each)
   OR
- Add dynamic nickname (Adds the player’s nickname to the chat history)
  - Anonymous mode (User1, User2, User3)
  - Public mode (Scout, Engineer, Walter Hartwell White)

In practice, I've observed that people generally prefer more privacy rather than sharing the same chat space with others. Take Roleplaying as an example: a user can have a cute little conversation with the chatbot and someone interrupts it, and now the chatbot thinks that the user they were just talking to said something devious, the outcome that no user desires.

Example of the current way the chat history is handled:
User: Hello.
Assistant: Greetings! As an artificial intelligence, I am fully at your service. Feel free to inquire!
User (Different person): Do you speak French?
Assistant: I am proficient in several languages, French being one of them, so yes!
User: Can you engage in roleplaying?
Assistant: As an artificial intelligence, I am equipped to handle a variety of tasks, including engaging in roleplay across multiple languages and French.

**Comment by teufortressIndustries** [comment]
I edited my previous message to clarify the issue.

**Comment by dborodin836** [comment]
You can now use `!pc` for private chats with OpenAI and `!pcc` for TextgenWebUI, which should help keep conversations separate and more personalized. I've decided to keep the global chat option available as well, under the original commands, just in case there are users out there who enjoy the chaos. Also, the syntax for the `!clear` command has been updated to reflect these changes.

**Comment by teufortressIndustries** [comment]
Ty! I ran some tests in-game and it works.
